# ----------------------------------------------------------------------------
# Custom SCC for Ingress NGINX
# This SCC is used to allow the Ingress NGINX controller to run with the necessary permissions
# while still adhering to security best practices in OpenShift.
# ---------------------------------------------------------------------------
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ingress-nginx-scc
allowPrivilegedContainer: false # no fully privileged containers
allowHostDirVolumePlugin: false # disallow hostPath
allowHostNetwork: false
allowHostPID: false
allowHostPorts: true
allowHostIPC: false
defaultAddCapabilities: [] # don’t add anything by default
requiredDropCapabilities:
  - ALL # drop all caps unless explicitly allowed
allowedCapabilities:
  - NET_BIND_SERVICE # needed to bind to ports 80/443
volumes:
  - configMap
  - secret
  - downwardAPI
  - emptyDir
  - projected
readOnlyRootFilesystem: false # controller needs writeable FS for logs, temp
runAsUser:
  type: MustRunAsNonRoot # allow any non-root UID (101,65532…)
seLinuxContext:
  type: MustRunAs # keep usual OpenShift SELinux confinement
fsGroup:
  type: RunAsAny # allow pods to choose group for FS mounts
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - "runtime/default" # use container’s default seccomp
users:
  - system:serviceaccount:ingress-nginx:ingress-nginx
  - system:serviceaccount:ingress-nginx:ingress-nginx-admission
priority: 10 # ensure this SCC is evaluated before the built-in restricted

