[server]
hostname = "tm.wso2.com"
server_role = "traffic-manager"
offset = "0"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://apim-puppet-db.mysql.database.azure.com:3306/apim_db?useSSL=false"
username = "apimadmin"
password = "apimadmin"
driver = "com.mysql.cj.jdbc.Driver"

[database.apim_db.pool_options]
validationQuery = "SELECT 1"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://apim-puppet-db.mysql.database.azure.com:3306/shared_db?useSSL=false"
username = "sharedadmin"
password = "sharedadmin"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db.pool_options]
validationQuery = "SELECT 1"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
#[apim.key_manager]
#service_url = "https://cp.wso2.com:${mgt.transport.https.port}${carbon.context}services/"

#[apim.oauth_config]
#revoke_endpoint = ""
#enable_token_encryption = false
#enable_token_hashing = false

# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://cp.wso2.com:9443/services/"
event_listening_endpoints = ["tcp://cp.wso2.com:5672"]

[qpid.heartbeat]
delay = 60
timeout_factor = 2.0